[theme]
primaryColor = "#9EF01A"
backgroundColor = "#0b1e33"
secondaryBackgroundColor = "#152b45"
textColor = "#FFFFFF"
font = "sans serif"

[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = true
fileWatcherType = "poll"
runOnSave = true
