[theme]
primaryColor = "#9EF01A"
backgroundColor = "#05192d"
secondaryBackgroundColor = "#0e243a"
textColor = "#ffffff"
font = "sans serif"

[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = true
fileWatcherType = "poll"
runOnSave = true
