[theme]
primaryColor = "#9EF01A"
backgroundColor = "#4169E1"
secondaryBackgroundColor = "#12263a"
textColor = "#FFFFFF"
font = "sans serif"

[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = true
fileWatcherType = "poll"
runOnSave = true
