[theme]
primaryColor = "#7d4cfc"
backgroundColor = "#0e1117"
secondaryBackgroundColor = "#1d2129"
textColor = "#fafafa"
font = "sans serif"

[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = true
fileWatcherType = "poll"
runOnSave = true
